//
// Generated file, do not edit! Created by opp_msgtool 6.0 from veins/modules/messages/AckTimeOutMessage.msg.
//

#ifndef __VEINS_ACKTIMEOUTMESSAGE_M_H
#define __VEINS_ACKTIMEOUTMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class AckTimeOutMessage;

}  // namespace veins


namespace veins {

/**
 * Class generated from <tt>veins/modules/messages/AckTimeOutMessage.msg:25</tt> by opp_msgtool.
 * <pre>
 * message AckTimeOutMessage
 * {
 *     // The corresponding WSM's tree id
 *     unsigned long wsmId = -1;
 *     // Access category on which the AckTimer is set
 *     int ac = -1;
 * }
 * </pre>
 */
class VEINS_API AckTimeOutMessage : public ::omnetpp::cMessage
{
  protected:
    unsigned long wsmId = -1;
    int ac = -1;

  private:
    void copy(const AckTimeOutMessage& other);

  protected:
    bool operator==(const AckTimeOutMessage&) = delete;

  public:
    AckTimeOutMessage(const char *name=nullptr, short kind=0);
    AckTimeOutMessage(const AckTimeOutMessage& other);
    virtual ~AckTimeOutMessage();
    AckTimeOutMessage& operator=(const AckTimeOutMessage& other);
    virtual AckTimeOutMessage *dup() const override {return new AckTimeOutMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual unsigned long getWsmId() const;
    virtual void setWsmId(unsigned long wsmId);

    virtual int getAc() const;
    virtual void setAc(int ac);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AckTimeOutMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AckTimeOutMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::AckTimeOutMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::AckTimeOutMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ACKTIMEOUTMESSAGE_M_H

